# Generated by Django 5.2 on 2025-05-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_id',
        ),
    ]
