# Generated by Django 5.2 on 2025-05-13 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_userprofile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_bind_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
