# Generated by Django 5.2 on 2025-05-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_telegram_bind_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_bind_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_id',
        ),
    ]
